name: Build and publish image

description: Builds and pushes the Docker image.

inputs:
  gcloud-project:
    description: "GCP project to use for the build"
    required: true
  gcloud-email:
    description: "GCP account email to use for the build"
    required: true
  gcloud-key:
    description: "GCP account key to use for the build"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set env vars
      shell: bash
      run: |
        echo "GCLOUD_PROJECT=${{ inputs.gcloud-project }}" >> $GITHUB_ENV
        echo "IMAGE_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "VERSION=$DOCKER_IMAGE_VERSION" >> $GITHUB_ENV

    - uses: google-github-actions/setup-gcloud@master
      with:
        version: "270.0.0"
        service_account_email: ${{ inputs.gcloud-email }}
        service_account_key: ${{ inputs.gcloud-key }}

    - shell: bash
      run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Build the Docker image
    - name: Build
      shell: bash
      run: docker build --build-arg APP_VERSION=$VERSION -t image .

    # Push the Docker image to Google Container Registry
    - name: Publish
      shell: bash
      run: |
        IMAGE_ID=gcr.io/$GCLOUD_PROJECT/$IMAGE_NAME
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag image $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
