name: Build and publish image

description: Builds and pushes the Docker image.

inputs:
  gcloud-project:
    description: "GCP project to use for the build"
    required: true
  gcloud-credentials:
    description: "Credentials corresponding to the service account (json)"
    required: true
  build-args:
    description: "Build args for the docker image"
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set env vars
      shell: bash
      run: |
        echo "GCLOUD_PROJECT=${{ inputs.gcloud-project }}" >> $GITHUB_ENV
        echo "IMAGE_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
        echo "VERSION=$DOCKER_IMAGE_VERSION" >> $GITHUB_ENV

    - name: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: "${{ inputs.gcloud-credentials }}"

    - name: Setup Gcloud
      uses: google-github-actions/setup-gcloud@v0

    - name: Set up docker auth
      shell: bash
      run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker gcr.io,eu.gcr.io,europe-west3-docker.pkg.dev

    - name: Check if already an image built for the commit
      shell: bash
      run: |
        CHECK_IMAGE_TAG=$(gcloud container images list-tags europe-west3-docker.pkg.dev/${GCLOUD_PROJECT}/${IMAGE_NAME}/${IMAGE_NAME} | grep "$COMMIT_HASH_SHORT" | awk '{ print $2}' | sed 's/,.*//' | xargs || true)
        echo "CHECK_IMAGE_TAG=$CHECK_IMAGE_TAG" >> $GITHUB_ENV
      env:
        REGISTRY: "${{ inputs.registry }}"

    # Build the Docker image
    - name: Build
      shell: bash
      run: |
        if [[ "$CHECK_IMAGE_TAG" == "" ]]; then
          if [[ "$BUILD_ARGS" == "" ]]; then
            docker build --build-arg APP_VERSION=$VERSION -t image .
          else
            docker_cmd="docker build $BUILD_ARGS -t image ."
            $docker_cmd
          fi
        fi
      env:
        BUILD_ARGS: "${{ inputs.build-args }}"

    # Push the Docker image to Google Container Registry
    - name: Publish
      shell: bash
      run: |
        IMAGE_ID=europe-west3-docker.pkg.dev/${GCLOUD_PROJECT}/${IMAGE_NAME}/${IMAGE_NAME}
        echo "IMAGE_ID=${IMAGE_ID}"
        echo "VERSION=${VERSION}"

        if [[ "$CHECK_IMAGE_TAG" == "" ]]; then
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
        else
          gcloud container images add-tag -q  europe-west3-docker.pkg.dev/${GCLOUD_PROJECT}/${IMAGE_NAME}/${IMAGE_NAME}:${CHECK_IMAGE_TAG}  europe-west3-docker.pkg.dev/${GCLOUD_PROJECT}/${IMAGE_NAME}/${IMAGE_NAME}:$VERSION
        fi
      env:
        REGISTRY: "${{ inputs.registry }}"
