name: 'Node setup action'

description: 'Install Node.js and NPM with deps'

inputs:
    node-version:
        description: 'Node version to setup with'
        required: true
        default: '16'
    node-auth-token:
        description: 'Token to use for NPM authentication'
        required: true

runs:
    using: 'composite'
    steps:
        - uses: actions/setup-node@v3
          with:
              node-version: ${{ inputs.node-version }}
              registry-url: 'https://npm.pkg.github.com'
              cache: 'npm'

        - name: Install deps
          run: npm ci
          shell: bash
          env:
              NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
