name: Runs ESLint and Prettier for Typescript projects

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use for the lint job"
        type: string
        required: true
    secrets:
      node-auth-token:
        description: "Node auth token"
        required: true

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: myos-finance/.github/.github/actions/node-setup@v0
        with:
          node-version: ${{ inputs.node-version }}
          node-auth-token: ${{ secrets.node-auth-token }}

      - name: ESLint
        run: npm run eslint

      - name: prettier
        run: npm run prettier:check
