name: Runs ESLint and Prettier for Typescript projects

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node version to use for the lint job"
        type: string
        required: true

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: myos-finance/.github/.github/actions/node-setup@main
        with:
          - node-version: ${{ inputs.node-version }}
          - node-auth-token: ${{ secrets.CI_TOKEN }}

      - name: ESLint
        run: npm run eslint

      - name: prettier
        run: npm run prettier:check
